-- AvroraMU Event Manager
-- Safe incremental migration for comment reactions.
-- Preserves every existing profile, event, comment, and authentication user.

begin;

create table if not exists public.comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction_type text not null check (reaction_type in ('like', 'love', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

create index if not exists idx_comment_reactions_comment_id
on public.comment_reactions(comment_id);

create index if not exists idx_comment_reactions_user_id
on public.comment_reactions(user_id);

drop trigger if exists comment_reactions_set_updated_at on public.comment_reactions;
create trigger comment_reactions_set_updated_at
before update on public.comment_reactions
for each row execute function public.set_updated_at();

alter table public.comment_reactions enable row level security;

drop policy if exists "Everyone can read comment reactions" on public.comment_reactions;
drop policy if exists "Users can create own comment reactions" on public.comment_reactions;
drop policy if exists "Users can update own comment reactions" on public.comment_reactions;
drop policy if exists "Users can delete own comment reactions" on public.comment_reactions;
drop policy if exists "Admins can create comment reactions" on public.comment_reactions;
drop policy if exists "Admins can update comment reactions" on public.comment_reactions;
drop policy if exists "Admins can delete comment reactions" on public.comment_reactions;

create policy "Everyone can read comment reactions"
on public.comment_reactions for select to anon, authenticated
using (true);

create policy "Users can create own comment reactions"
on public.comment_reactions for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own comment reactions"
on public.comment_reactions for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own comment reactions"
on public.comment_reactions for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "Admins can create comment reactions"
on public.comment_reactions for insert to authenticated
with check (public.is_admin());

create policy "Admins can update comment reactions"
on public.comment_reactions for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete comment reactions"
on public.comment_reactions for delete to authenticated
using (public.is_admin());

grant select on public.comment_reactions to anon;
grant select, insert, update, delete on public.comment_reactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;

-- Read-only verification. Expected: RLS enabled and seven policies listed.
select c.relname as table_name, c.relrowsecurity as rls_enabled
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relname = 'comment_reactions';

select policyname, cmd, roles
from pg_policies
where schemaname = 'public' and tablename = 'comment_reactions'
order by policyname;
