-- AvroraMU Event Manager: database schema
-- Run first in the Supabase SQL Editor.

create extension if not exists pg_trgm;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text check (char_length(full_name) between 2 and 100),
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null check (char_length(name) between 2 and 80),
  description text,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_categories_name_lower_unique
on public.categories (lower(name));

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete restrict,
  title text not null check (char_length(title) between 2 and 150),
  short_description text check (char_length(short_description) <= 240),
  description text not null,
  event_date timestamptz not null,
  location text,
  max_participants integer check (max_participants is null or max_participants > 0),
  image_url text,
  rules_file_url text,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_name text not null check (character_name ~ '^[A-Za-z0-9_-]{3,20}$'),
  character_class text not null check (character_class in ('Dark Wizard', 'Dark Knight', 'Fairy Elf', 'Magic Gladiator', 'Dark Lord', 'Summoner', 'Rage Fighter')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_events_category_id on public.events(category_id);
create index if not exists idx_events_created_by on public.events(created_by);
create index if not exists idx_events_active_date on public.events(is_active, event_date);
create index if not exists idx_events_title_trgm on public.events using gin(title gin_trgm_ops);
create index if not exists idx_registrations_event_id on public.registrations(event_id);
create index if not exists idx_registrations_user_id on public.registrations(user_id);
create index if not exists idx_registrations_status on public.registrations(status);
create index if not exists idx_comments_event_created on public.comments(event_id, created_at desc);
create index if not exists idx_comments_user_id on public.comments(user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at before update on public.comments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    'user'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

-- Serializes registrations per event and enforces date/capacity at database level.
create or replace function public.validate_event_registration()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  target_event public.events%rowtype;
  current_count integer;
begin
  select * into target_event from public.events where id = new.event_id for update;
  if not found then raise exception 'Event does not exist'; end if;
  if not target_event.is_active then raise exception 'Event is not active'; end if;
  if target_event.event_date <= now() then raise exception 'Registration has closed'; end if;
  select count(*) into current_count from public.registrations where event_id = new.event_id;
  if target_event.max_participants is not null and current_count >= target_event.max_participants then
    raise exception 'Event is full';
  end if;
  if new.status is null then new.status := 'pending'; end if;
  return new;
end;
$$;

drop trigger if exists registrations_validate_event on public.registrations;
create trigger registrations_validate_event before insert on public.registrations
for each row execute function public.validate_event_registration();

-- Exposes only an aggregate, never participant details, to public event pages.
create or replace function public.get_event_registration_count(target_event_id bigint)
returns bigint language sql stable security definer set search_path = '' as $$
  select count(*)
  from public.registrations r
  join public.events e on e.id = r.event_id
  where r.event_id = target_event_id
    and e.is_active = true;
$$;
